### ISSUE TITLE
Values Method Indexing Error

### ISSUE THREAD

**Issue by mlouis9** [CORE-GATECH-GROUP/xs-interface#85]
## The Error ##
The universes.values() method seems to no longer be working properly as the result of recent changes. For example, running the template:
```
"values"{infflx, tmod=-1, boron=1600, crod=-1, tfuel=-1, time=0.5 history=his_nom [0]}
```
Throws an error:
```
Traceback (most recent call last):
  File "/storage/home/hcoda1/3/mlouis9/LEU+/example/xs_gen_with_xsinterface.py", line 15, in <module>
    xs.Read(readTemplate=True) # Read xs data and templates and populate data
  File "/storage/home/hcoda1/3/mlouis9/xs-interface/xsInterface/functions/main.py", line 172, in Read
    ReadTemplate(tmplfile, self.universes, self._formats,
  File "/storage/home/hcoda1/3/mlouis9/xs-interface/xsInterface/functions/readtemplate.py", line 107, in ReadTemplate
    dataPopulated = _PopulateValues(dataClean, universes, formats, uservals)
  File "/storage/home/hcoda1/3/mlouis9/xs-interface/xsInterface/functions/readtemplate.py", line 265, in _PopulateValues
    universes.Values(univId, attr, **states)[attr]
  File "/storage/home/hcoda1/3/mlouis9/xs-interface/xsInterface/containers/universes.py", line 368, in Values
    vals[istate] = statevals
IndexError: list assignment index out of range
```
Where the states and histories are defined via:
```
set branches 4
boron  -1, 0, 1600
tfuel  -1, 1200, 600
crod   -1, 1
tmod   -1

set histories 5
HIS_nom     750, 0, 900, 580
HIS_TM550   750, 0, 900, 550
HIS_TM600   750, 0, 900, 600
HIS_1600B  1600, 0, 900, 580
HIS_tfu600  750, 0, 600, 580
```
But the template does not error when only the nominal state is accessed, i.e.
```
"values"{infflx, tmod=-1, boron=-1, crod=-1, tfuel=-1, time=0.5 history=his_nom [0]}
```
## Possible Cause ##
When printing out the dictionary containing the states and attribute values (pdDict in universes.py):
```
{'history': {12: 'his_nom'}, 'time': {12: 0.5}, 'boron': {12: 1600.0}, 'tfuel': {12: -1.0}, 'crod': {12: -1.0}, 'tmod': {12: -1.0}, 'infflx': {12: array([3.45157e+17, 1.04654e+16])}}
```
we see that the keys of the item dictionaries (i.e. {12: 'his_nom'} has key 12) have keys of 12, and when the list for holding the value dictionary (for the state values) is created, it is assumed that the state index will always be within nstates - 1 (where nstates is the number of states values are requested for). E.g.
```
vals = [None]*nstates  # a list to hold states and not attrs
                for istate, statevals in valsDict.items():
                    vals[istate] = statevals
```
In this case, only a single value is being requested, for a single state, so nstates is 1. For the nominal case, the pdDict is:
```
{'history': {0: 'his_nom'}, 'time': {0: 0.5}, 'boron': {0: -1.0}, 'tfuel': {0: -1.0}, 'crod': {0: -1.0}, 'tmod': {0: -1.0}, 'infflx': {0: array([2.45368e+17, 1.41838e+16])}}
```
where we see that the index is not out of range. Maybe there is some issue with indexing when generating the pdDict, or maybe the issue is with the incorrect post-processing of it.

### Note ###
Other aspects of the post-processing  of the pdDict explicitly rely on the presence of the key "0", e.g.
<pre>
if <b>valsDict[0]</b>.ndim == 2:
      ng = len(<b>valsDict[0][0]</b>)  # number of values
      ng = int(ng*ng)
      # square matrices (e.g., scattering)
      if key not in self.squareattrs[univId]:
          self.squareattrs[univId] = self.squareattrs[univId]+[key]
      vals = np.empty((nstates, ng))  # reset a matrix
      for istate, statevals in valsDict.items():
          vals[istate, :] = statevals.flatten()
  else:
      ng = len(<b>valsDict[0]</b>)  # number of values
      vals = np.empty((nstates, ng))  # reset a matrix
      for istate, statevals in valsDict.items():
          vals[istate, :] = statevals
</pre>

**Comment by DanKotlyar** [comment]
Fixed and working

**Comment by DanKotlyar** [comment]
I am closing this issue as it is working now

**Comment by mlouis9** [comment]
I just pulled the latest version of the repo and ran my input and it doesn't seem to work for this input setup: https://gtvault-my.sharepoint.com/:f:/g/personal/mlouis9_gatech_edu/Ejz2aCklSKBMru0BSLtwLuQBbQTFszvB_SO0zV9aMCqv_w?e=5ayzWp. But with the changes made in the linked PR, it runs fine. Maybe there's something strange with my input - would you mind to look through it (when you get a chance) to make sure everything is valid?

**Comment by mlouis9** [comment]
Nevermind, it looks like I pulled from my fork instead of the core repo; now it's working fine. Thanks for implementing this bug fix!

**Comment by DanKotlyar** [comment]
Great. Thanks!

-------------------------------------------------------------------------
Dan Kotlyar

Associate Professor
Georgia Institute of Technology
G.W.Woodruff School of Mechanical Engineering
Nuclear and Radiological Engineering Program
​770 State St NW<https://maps.google.com/?q=770+State+St+NW&entry=gmail&source=g>, Atlanta, GA 30332
Boggs Bldg 3-73  |  Phone: +1.404.385.5372
​http://pwp.gatech.edu/core/<http://pwp.gatech.edu/core/>
